import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme_provider";
import NavBar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="min-h-screen transition-colors duration-500 bg-[#d2e2f9] dark:bg-gradient-to-br dark:from-slate-900 dark:via-purple-900 dark:to-slate-900">
              <NavBar/>
              {/* <div className="px-5 pt-14 mx-auto max-w-3xl"> */}
              <div>
                {children}
              </div>
            </main>
            <Toaster />
          </ThemeProvider>
      </body>
    </html>
  );
}
